### ISSUE TITLE
[BUG&建议] 指向芙芙工具箱的社交媒体的网站错误 / 一些网站相关问题与建议

### ISSUE THREAD

**Issue by DuckDuckStudio** [kisslove/chinese-independent-developer-site#2]
这是一个很好的网页，但我在其中搜索[我自己的项目](https://github.com/1c7/chinese-independent-developer?tab=readme-ov-file#%E9%B8%AD%E9%B8%AD%E3%82%AB%E3%83%A2%E5%8E%A6%E9%97%A8---github-%E4%B8%AA%E4%BA%BA%E7%BD%91%E9%A1%B5-xtwitter)时遇到了点问题。
我搜到的提交者并非项目的开发者，同时三个社交网站的链接都是错误的，也与我无关...

![image](https://github.com/kisslove/chinese-independent-developer-site/assets/89643991/2f3ffcdc-2944-4a56-af5b-05a3745367f3)

> - 推特与GitHub指向 uestccokey
> - 官网指向 [阿Q围棋](http://www.ezandroid.cn/)
> - 网站上提交者为 奔跑的小山猪。我最开始通过Issue提交，后面有用[PR](https://github.com/1c7/chinese-independent-developer/pull/338)修改，但我与网站上的提交者没有任何联系。

_(我并未在网站上搜到[我的另一个项目](https://github.com/1c7/chinese-independent-developer/blob/master/README-Programmer-Edition.md#%E9%B8%AD%E9%B8%AD%E3%82%AB%E3%83%A2%E5%8E%A6%E9%97%A8---github-%E4%B8%AA%E4%BA%BA%E7%BD%91%E9%A1%B5-xtwitter)（通过[1c7/chinese-independent-developer #356](https://github.com/1c7/chinese-independent-developer/pull/356)添加），所以我无法确定其他项目是否会出现这个情况)_

---

关于建议，我觉得可以在没有社交媒体时隐藏“社交媒体：”，否则看起来有点怪。
> 或者使“社交媒体”的颜色像“提交者”的颜色一样？

![image](https://github.com/kisslove/chinese-independent-developer-site/assets/89643991/500666ef-6b4e-4fad-8cdd-5d847c2e8cd2)
可以试着将开发者的名称和地区分开来。

---

关于我遇到的一些问题：
更多介绍不会以链接的形式显示：
![image](https://github.com/kisslove/chinese-independent-developer-site/assets/89643991/343940dd-b50d-41dc-8a4c-ce08822a45ea)
意外的添加日期：
![image](https://github.com/kisslove/chinese-independent-developer-site/assets/89643991/ca59931d-233d-416e-9dfd-5231e9065ec2)
> 与上架日期不同

**Comment by kisslove** [comment]
感谢反馈，问题和建议已收到，会在近期做修改

**Comment by kisslove** [comment]
bug，已修复，其他建议我们也会做修改
